language: generic
sudo: required

before_install:
  - sudo ./.travis-update-docker-compose

services:
  - docker

before_script:
  - docker-compose build
  - docker version

script:
  - ./test.sh

addons:
  apt:
    packages:
      - docker-ce