language: php
sudo: required

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.24.2/docker-compose-`uname -s`-`uname -m` > mktemp
  - chmod 755 mktemp
  - sudo mv mktemp docker-compose

services:
  - docker

before_script:
  - docker-compose build
  - docker version

script:
  - composer update
  - docker-compose up -d
  - docker-compose run --user $(id -u):$(id -g) nogues-php ./vendor/phpunit/phpunit/phpunit

addons:
  apt:
    packages:
      - docker-ce