version: "3"
services:

  nogues-php:
    container_name: nogues-php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    links:
      - nogues-db
    ports:
      - "9090:80"
    volumes:
      - ./:/app
      - ./docker/php/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/:/etc/php/7.3/fpm/conf.d/"

  nogues-db:
    container_name: nogues-db
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 6033:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  nogues-db-admin:
    container_name: nogues-db-admin
    image: adminer
    restart: always
    ports:
      - 8080:8080